# Initial values 
# Initial values for delta can be generated by WinBUGS and NIMBLE(?) 

"d" <-
  c( NA, 0)

"mu" <- 
   c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)


"A" <-0



#NIMBLE: nur eine Kette
# zusätzlich noch einzufügen:
