# Initial values 
# Initial values for delta can be generated by WinBUGS and NIMBLE(?) 

"d" <-
  c( NA, 0)

"sd" <-
  c( 1)

"mu" <- 
   c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)


"A" <-0

"delta" <- 
  structure(c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            .Dim = as.integer(c(22,2)))



#NIMBLE: nur eine Kette
# zusätzlich noch einzufügen:
